In [1]:
import numpy as np
from sklearn.datasets import load_boston,make_regression
from sklearn.model_selection import train_test_split

In [2]:
boston=load_boston()
x=boston.data
y=boston.target

c:\Users\Armaan\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset 

In [3]:
x,y=make_regression(n_samples=100,n_features=1,noise=20,random_state=4)

In [4]:
print(boston.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [5]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0)

In [6]:
def cost(x1,y,w,b):
    cost=0
    M=len(x1)
    for i in range(M):
        cost+=(1/M)*((y[i]-np.dot(x1[i].T,w)-b)**2)
    return cost

In [7]:
def stepgradient(xi,y,lr,w,b):
    M,N=xi.shape
    wn=np.zeros(N)
    bn=0
    for i in range(M):
        for j in range(N):
            wn[j]+=(-2/M)*(y[i]-np.sum(np.dot(xi[i].T,w))-bn)*(xi[i][j])
            bn+=(-2/M)*(y[i]-np.sum(np.dot(xi[i].T,w))-bn)
    w_new=w+lr*wn
    b_new=b+lr*bn
    return w_new,b_new

In [8]:
def gradientdescent(x_train,y,lr,itr):
    w=np.zeros(x_train.shape[1])
    b=0
    for i in range(itr):
        w,b=stepgradient(x_train,y,lr,w,b)
        print(" Cost=",cost(x_train,y,w,b))
    return w,b

In [9]:
def fit(x_train,y_train,lr,itr):
    n_samples,n_features=x_train.shape
    weights=np.zeros(n_features)
    bias=0
    for i in range(itr):
        y_predict=np.dot(x_train,weights)+bias
        dw=(-2/n_samples)*np.dot(x_train.T,(y_train-y_predict))
        db=(-2/n_samples)*np.sum(y_train-y_predict)
        weights=weights-lr*dw
        bias=bias-lr*db
        print("cost=",cost(x_train,y_train,weights,bias))
        weights,bias=gradientdescent(x_train,y_train,lr,itr)
    return weights,bias

In [10]:
def predict(x,w,b):
    y_pred=np.dot(x,w)+b
    return y_pred

In [11]:
def mse(y_pred,y_test):
    return np.mean((y_test-y_pred)**2)

In [12]:
w,b=fit(x_train,y_train,lr=.1,itr=100)

cost= 3808.943336170967
cost= 2568.684841123736
cost= 1768.8730253255494
cost= 1252.5190147981036
cost= 918.7948464487749
cost= 702.8696417592345
cost= 563.011155383819
cost= 472.32574846503957
cost= 413.4628686393532
cost= 375.2162780002478
cost= 350.3401989636246
cost= 334.1445152457539
cost= 323.590095059501
cost= 316.70553403558677
cost= 312.2107016558603
cost= 309.2734961446294
cost= 307.3524992489398
cost= 306.0950856262999
cost= 305.2713718332876
cost= 304.73135337494017
cost= 304.37706056987787
cost= 304.14445242650265
cost= 303.991631152567
cost= 303.8911634153006
cost= 303.8250726041834
cost= 303.78157001041296
cost= 303.75291919262827
cost= 303.73403948983844
cost= 303.7215920998956
cost= 303.7133814882096
cost= 303.7079630240789
cost= 303.70438560265086
cost= 303.70202269194226
cost= 303.7004613490979
cost= 303.6994292679998
cost= 303.69874679552777
cost= 303.6982953516441
cost= 303.69799663347084
cost= 303.697798913276
cost= 303.69766800576815
cost= 303.69758131053914
cost

In [13]:
y_pred=predict(x_test,w,b)
print(mse(y_pred,y_test))

1.0496407978738549e+19


In [14]:
y_pred

array([-3.13831529e+09, -4.10301558e+09, -4.49066365e+09,  4.68002257e+09,
       -2.44877494e+09, -2.15487142e+09, -6.43359910e+09, -1.88335934e+09,
       -4.35991345e+09, -2.44876473e+09,  7.65710756e+08, -4.52776013e+08,
       -2.77031674e+09, -1.07020682e+09, -3.99003073e+09, -2.33359270e+09,
        2.43601295e+09,  6.44784433e+09, -2.04548001e+09,  2.39330933e+09,
       -1.17986576e+09,  4.94192075e+08, -1.47670123e+09, -3.03159790e+09,
        3.41593664e+09])

In [15]:
y_test

array([  24.13154879,   64.66264562,   63.15463302, -158.28468928,
          9.55981705,   24.2973507 ,  141.46769811,   41.12497399,
         52.1696979 ,   34.44108322,  -56.55140067,  -12.46435171,
         19.1701073 ,   31.80766772,   53.81362958,    0.98036703,
       -101.89829601, -181.34840044,    9.20267903,  -95.34105851,
         -3.80893607,  -21.4183161 ,    6.05472009,   28.14443518,
        -97.2027103 ])

In [16]:
def score(y_predict,y_true):
    y_mean=np.mean(y_true)
    return 1-(np.sum((y_true-y_predict)**2))/(np.sum((y_true-y_mean)**2))

In [17]:
print(score(y_pred,y_test))

-2013757192735778.2


array([ 6,  9, 12])