# Fertilizer Reccomendation

In [63]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
import tensorflow as tf

In [64]:
data=pd.read_csv("C:\\Users\\Armaan\\OneDrive\\Desktop\\WORKSPACE\\Machine_Learning\\Datasets\\farmAid\\fertilizerReccomendation\\Fertilizer Prediction.csv",index_col=False)
data.head()

Temparature  Humidity   Moisture Soil Type  Crop Type  Nitrogen  Potassium  \
0           26         52        38     Sandy      Maize        37          0   
1           29         52        45     Loamy  Sugarcane        12          0   
2           34         65        62     Black     Cotton         7          9   
3           32         62        34       Red    Tobacco        22          0   
4           28         54        46    Clayey      Paddy        35          0   

   Phosphorous Fertilizer Name  
0            0            Urea  
1           36             DAP  
2           30        14-35-14  
3           20           28-28  
4            0            Urea

In [65]:
classes=['Urea', 'DAP', '14-35-14', '28-28', '17-17-17', '20-20', '10-26-26']

In [66]:
data["Fertilizer Name"]=data["Fertilizer Name"].map({'Urea':0, 'DAP':1, '14-35-14':2, '28-28':3, '17-17-17':4, '20-20':5, '10-26-26':6})

data["Soil Type"]=data["Soil Type"].map({'Sandy':0, 'Loamy':1, 'Black':2, 'Red':3, 'Clayey':4})

data["Crop Type"]=data["Crop Type"].map({'Maize':0, 'Sugarcane':1, 'Cotton':2, 'Tobacco':3, 'Paddy':4, 'Barley':5, 'Wheat':6, 'Millets':7,
                                          'Oil seeds':8, 'Pulses':9, 'Ground Nuts':10})

In [67]:
y=data["Fertilizer Name"]
x=data.drop(['Fertilizer Name'],axis=1)

In [69]:
y

0     0
1     1
2     2
3     3
4     0
     ..
94    3
95    6
96    0
97    1
98    5
Name: Fertilizer Name, Length: 99, dtype: int64

In [75]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0,test_size=0.2,shuffle=True)

In [79]:
y_test

26    2
86    6
2     2
55    3
75    2
92    0
16    0
73    0
54    4
94    3
53    1
91    6
78    6
13    3
7     0
30    3
22    1
24    5
33    2
8     3
Name: Fertilizer Name, dtype: int64

In [106]:
model=tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape=[8],dtype=tf.float32),)
model.add(tf.keras.layers.Dense(48,activation="relu"))
model.add(tf.keras.layers.Dense(32,activation="relu"))
model.add(tf.keras.layers.Dense(7,activation="softmax"))
model.compile(loss=tf.keras.losses.categorical_crossentropy,optimizer=tf.keras.optimizers.Adam(),metrics=["accuracy","mse"])

In [114]:
model.fit(x_train,tf.one_hot(y_train,depth=7),epochs=10)

Epoch 1/10
3/3 [==============================] - 0s 3ms/step - loss: 0.1271 - accuracy: 0.9873 - mse: 0.0063
Epoch 2/10
3/3 [==============================] - 0s 3ms/step - loss: 0.1247 - accuracy: 0.9873 - mse: 0.0061
Epoch 3/10
3/3 [==============================] - 0s 2ms/step - loss: 0.1204 - accuracy: 0.9873 - mse: 0.0057
Epoch 4/10
3/3 [==============================] - 0s 3ms/step - loss: 0.1178 - accuracy: 0.9873 - mse: 0.0056
Epoch 5/10
3/3 [==============================] - 0s 2ms/step - loss: 0.1155 - accuracy: 0.9873 - mse: 0.0055
Epoch 6/10
3/3 [==============================] - 0s 2ms/step - loss: 0.1135 - accuracy: 0.9873 - mse: 0.0054
Epoch 7/10
3/3 [==============================] - 0s 3ms/step - loss: 0.1115 - accuracy: 0.9873 - mse: 0.0053
Epoch 8/10
3/3 [==============================] - 0s 2ms/step - loss: 0.1091 - accuracy: 0.9873 - mse: 0.0051
Epoch 9/10
3/3 [==============================] - 0s 3ms/step - loss: 0.1073 - accuracy: 1.0000 - mse: 0.0049
Epoch 10/1

In [115]:
model.evaluate(x_test,tf.one_hot(y_test,depth=7))

1/1 [==============================] - 0s 132ms/step - loss: 0.1914 - accuracy: 1.0000 - mse: 0.0116


[0.191437765955925, 1.0, 0.011584097519516945]

In [116]:
y_pred=model.predict(x_test)

1/1 [==============================] - 0s 46ms/step


In [117]:
y_pred[0]

array([1.2026998e-06, 2.6209524e-02, 6.8367851e-01, 1.1221911e-01,
       1.3351232e-01, 3.4900233e-03, 4.0889278e-02], dtype=float32)

In [118]:
ypred=np.argmax(y_pred,axis=1)
ypred

array([2, 6, 2, 3, 2, 0, 0, 0, 4, 3, 1, 6, 6, 3, 0, 3, 1, 5, 2, 3],
      dtype=int64)

In [119]:
ypred.shape

(20,)

In [ ]:
# y_test=np.argmax(np.array(y_test),axis=1)
# y_test

In [121]:
print(classification_report(y_test,ypred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         2
           2       1.00      1.00      1.00         4
           3       1.00      1.00      1.00         5
           4       1.00      1.00      1.00         1
           5       1.00      1.00      1.00         1
           6       1.00      1.00      1.00         3

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [122]:
print(confusion_matrix(np.array(y_test),np.array(ypred)))

[[4 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 4 0 0 0 0]
 [0 0 0 5 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 3]]


In [105]:
model.save("fertilizerPrediction.h5")