In [23]:
import numpy as np 
import pandas as pd

In [24]:
df=pd.read_csv("survey.csv")

In [25]:
df.drop(['comments'], axis=1, inplace=True)
df.drop(['state'], axis=1, inplace=True)

df.drop(['Timestamp'], axis=1, inplace=True)
df.drop(['Country'], axis=1, inplace=True)

In [26]:
df['self_employed'] = df['self_employed'].fillna(df['self_employed'].mode()[0])
df['work_interfere'] = df['work_interfere'].fillna(df['work_interfere'].mode()[0])

In [27]:
unique_values_per_column = {}
for column in df.columns:
    unique_values_per_column[column] = df[column].unique()

In [28]:
unique_values_per_column['Age']

array([         37,          44,          32,          31,          33,
                35,          39,          42,          23,          29,
                36,          27,          46,          41,          34,
                30,          40,          38,          50,          24,
                18,          28,          26,          22,          19,
                25,          45,          21,         -29,          43,
                56,          60,          54,         329,          55,
       99999999999,          48,          20,          57,          58,
                47,          62,          51,          65,          49,
             -1726,           5,          53,          61,           8,
                11,          -1,          72], dtype=int64)

In [29]:
uncleaned_age_df = df[(df['Age'] < 21) | (df['Age'] > 44)]
len(uncleaned_age_df)
uncleaned_age_df['Age'].index

Int64Index([  18,   22,   38,   43,   75,   93,  112,  118,  129,  143,  150,
             178,  183,  282,  287,  292,  294,  297,  333,  335,  347,  364,
             372,  375,  390,  396,  419,  437,  466,  471,  475,  478,  482,
             484,  498,  505,  508,  516,  520,  527,  560,  574,  581,  592,
             606,  631,  639,  643,  652,  660,  679,  682,  687,  715,  734,
             749,  825,  826,  837,  856,  864,  870,  895,  898,  904,  905,
             909,  910,  911,  946,  952,  964,  968,  973,  989,  991,  994,
            1017, 1020, 1027, 1068, 1090, 1104, 1106, 1117, 1123, 1126, 1127,
            1159, 1164, 1174, 1182, 1186, 1211, 1220, 1221, 1236, 1257],
           dtype='int64')

In [30]:
df = df.drop(uncleaned_age_df['Age'].index)

In [31]:
df['Age'].unique()

array([37, 44, 32, 31, 33, 35, 39, 42, 23, 29, 36, 27, 41, 34, 30, 40, 38,
       24, 28, 26, 22, 25, 21, 43], dtype=int64)

In [32]:
for i in df.columns:
  print(i,df[i].unique())

Age [37 44 32 31 33 35 39 42 23 29 36 27 41 34 30 40 38 24 28 26 22 25 21 43]
Gender ['Female' 'M' 'Male' 'male' 'female' 'm' 'Male-ish' 'maile' 'Trans-female'
 'Cis Female' 'F' 'Cis Male' 'Woman' 'f' 'Mal' 'Male (CIS)'
 'queer/she/they' 'non-binary' 'Femake' 'woman' 'Make' 'Nah' 'Enby'
 'fluid' 'Genderqueer' 'Female ' 'Androgyne' 'Agender' 'cis-female/femme'
 'Guy (-ish) ^_^' 'male leaning androgynous' 'Man' 'msle' 'Neuter'
 'Female (trans)' 'queer' 'Mail' 'cis male' 'Malr' 'Male ' 'femail'
 'Cis Man' 'ostensibly male, unsure what that really means']
self_employed ['No' 'Yes']
family_history ['No' 'Yes']
treatment ['Yes' 'No']
work_interfere ['Often' 'Rarely' 'Never' 'Sometimes']
no_employees ['6-25' 'More than 1000' '26-100' '100-500' '1-5' '500-1000']
remote_work ['No' 'Yes']
tech_company ['Yes' 'No']
benefits ['Yes' "Don't know" 'No']
care_options ['Not sure' 'No' 'Yes']
wellness_program ['No' "Don't know" 'Yes']
seek_help ['Yes' "Don't know" 'No']
anonymity ['Yes' "Don't know" 'No

In [33]:
def clean_gender(g):
  male = ['male', 'Male','M', 'm', 'Male-ish', 'maile','Cis Male','Mal', 'Male (CIS)','Make','Male ', 'Man',
        'msle','cis male', 'Cis Man','Malr','Mail']
  female = ['Female', 'female','Cis Female', 'F','f','Femake', 'woman','Female ','cis-female/femme','Female (cis)','femail','Woman','female']
  # trans = ['Trans-female','something kinda male?','queer/she/they','non-binary','All','fluid', 'Genderqueer','Androgyne', 'Agender','Guy (-ish) ^_^',
  #       'male leaning androgynous','Trans woman','Neuter', 'Female (trans)','queer','ostensibly male, unsure what that really means','trans']
  if g in male:
    return "male"
  elif g in female:
    return "female"
  else:
    return "female"
  
def clean_employee(n):
  types=['1-5','6-25','26-100','100-500','500-1000','More than 1000']
  for i in range(len(types)):
    if types[i]==n:
      return i+1
  return 7
    
def ordinal_encoding(n,k=[]):
  for i in range(len(k)):
    if(n==k[i]):
      return i

def neumeric_yes_no(n):

  if n.lower()=="yes":
    return 0
  else:
    return 1

In [35]:
df["Gender"]=df["Gender"].apply(lambda x:clean_gender(x))
list=["Age","phys_health_interview","mental_vs_physical","mental_health_interview","supervisor","obs_consequence","phys_health_consequence"]
details=[]
for i in df.columns:
    dict={}
    if i not in list:
        dict[i]=df[i].unique()
        details.append(dict)
    if i!="Age":
        df[i]=df[i].apply(lambda x:ordinal_encoding(x,df[i].unique()))
    

In [ ]:
details

[{'Gender': array(['female', 'male'], dtype=object)},
 {'self_employed': array(['No', 'Yes'], dtype=object)},
 {'family_history': array(['No', 'Yes'], dtype=object)},
 {'treatment': array(['Yes', 'No'], dtype=object)},
 {'work_interfere': array(['Often', 'Rarely', 'Never', 'Sometimes'], dtype=object)},
 {'no_employees': array(['6-25', 'More than 1000', '26-100', '100-500', '1-5', '500-1000'],
        dtype=object)},
 {'remote_work': array(['No', 'Yes'], dtype=object)},
 {'tech_company': array(['Yes', 'No'], dtype=object)},
 {'benefits': array(['Yes', "Don't know", 'No'], dtype=object)},
 {'care_options': array(['Not sure', 'No', 'Yes'], dtype=object)},
 {'wellness_program': array(['No', "Don't know", 'Yes'], dtype=object)},
 {'seek_help': array(['Yes', "Don't know", 'No'], dtype=object)},
 {'anonymity': array(['Yes', "Don't know", 'No'], dtype=object)},
 {'leave': array(['Somewhat easy', "Don't know", 'Somewhat difficult',
         'Very difficult', 'Very easy'], dtype=object)},
 {'men

In [ ]:
# df["Gender"]=df["Gender"].apply(lambda x:clean_gender(x))
# df["self_employed"]=df["self_employed"].apply(lambda x:neumeric_yes_no(x))
# df["family_history"]=df["family_history"].apply(lambda x:neumeric_yes_no(x))
# df["treatment"]=df["treatment"].apply(lambda x:neumeric_yes_no(x))
# df["remote_work"]=df["remote_work"].apply(lambda x:neumeric_yes_no(x))
# df["tech_company"]=df["tech_company"].apply(lambda x:neumeric_yes_no(x))
# df["obs_consequence"]=df["obs_consequence"].apply(lambda x:neumeric_yes_no(x))
# df["no_employees"]=df["no_employees"].apply(lambda x:clean_employee(x))

In [ ]:
for i in df.columns:
    print(df[i].value_counts())

29    85
32    82
26    75
27    71
33    70
28    68
31    67
34    65
30    63
25    61
35    55
23    51
24    46
37    43
38    39
36    37
39    33
40    33
43    28
22    21
41    21
42    20
21    16
44    11
Name: Age, dtype: int64
1    910
0    251
Name: Gender, dtype: int64
0    1030
1     131
Name: self_employed, dtype: int64
0    697
1    464
Name: family_history, dtype: int64
0    582
1    579
Name: treatment, dtype: int64
3    683
2    191
1    158
0    129
Name: work_interfere, dtype: int64
0    277
2    267
1    255
3    165
4    140
5     57
Name: no_employees, dtype: int64
0    829
1    332
Name: remote_work, dtype: int64
0    950
1    211
Name: tech_company, dtype: int64
0    434
1    374
2    353
Name: benefits, dtype: int64
1    470
2    402
0    289
Name: care_options, dtype: int64
0    786
2    204
1    171
Name: wellness_program, dtype: int64
2    606
1    337
0    218
Name: seek_help, dtype: int64
1    753
0    347
2     61
Name: anonymity, dtype: int64
1    51

In [ ]:
# df=pd.get_dummies(df,columns=["Gender","work_interfere","seek_help","benefits","care_options","wellness_program","anonymity","leave","mental_health_consequence","coworkers","phys_health_consequence","supervisor","mental_health_interview","phys_health_interview","mental_vs_physical"])

In [36]:
df["Age"]=df["Age"].apply(lambda x:x/100)

In [37]:
for i in df.columns:
  print(i,df[i].unique())

Age [0.37 0.44 0.32 0.31 0.33 0.35 0.39 0.42 0.23 0.29 0.36 0.27 0.41 0.34
 0.3  0.4  0.38 0.24 0.28 0.26 0.22 0.25 0.21 0.43]
Gender [0]
self_employed [0 1]
family_history [0 1]
treatment [0 1]
work_interfere [0 1 2 3]
no_employees [0 1 2 3 4 5]
remote_work [0 1]
tech_company [0 1]
benefits [0 1 2]
care_options [0 1 2]
wellness_program [0 1 2]
seek_help [0 1 2]
anonymity [0 1 2]
leave [0 1 2 3 4]
mental_health_consequence [0 1 2]
phys_health_consequence [0 1 2]
coworkers [0 1 2]
supervisor [0 1 2]
mental_health_interview [0 1 2]
phys_health_interview [0 1 2]
mental_vs_physical [0 1 2]
obs_consequence [0 1]


In [ ]:
# y=df["treatment"]
# x=df.drop(["treatment","Gender_female","work_interfere_Often","seek_help_Don't know","benefits_Don't know","care_options_Not sure","wellness_program_Don't know","anonymity_Don't know","leave_Don't know","mental_health_consequence_Maybe","coworkers_No","phys_health_consequence_Maybe","supervisor_Some of them","mental_health_interview_Maybe","phys_health_interview_Maybe","mental_vs_physical_Don't know","mental_vs_physical_No"],axis=1)

In [38]:
y=df["treatment"]
x=df.drop(["treatment","phys_health_interview","mental_vs_physical","mental_health_interview","supervisor","obs_consequence","phys_health_consequence"],axis=1)

In [39]:
x

Age  Gender  self_employed  family_history  work_interfere  \
0     0.37       0              0               0               0   
1     0.44       0              0               0               1   
2     0.32       0              0               0               1   
3     0.31       0              0               1               0   
4     0.31       0              0               0               2   
...    ...     ...            ...             ...             ...   
1253  0.36       0              0               1               1   
1254  0.26       0              0               0               3   
1255  0.32       0              0               1               0   
1256  0.34       0              0               1               3   
1258  0.25       0              0               1               3   

      no_employees  remote_work  tech_company  benefits  care_options  \
0                0            0             0         0             0   
1                1            0             1         1             1   
2                0            0             0         2             1   
3                2            0             0         2             2   
4                3            1             0         0             1   
...            ...          ...           ...       ...           ...   
1253             1            0             1         1             1   
1254             2            0             0         2             1   
1255             2            1             0         0             2   
1256             1            0             0         0             2   
1258             2            0             1         0             2   

      wellness_program  seek_help  anonymity  leave  \
0                    0          0          0      0   
1                    1          1          1      1   
2                    0          2          1      2   
3                    0          2          2      2   
4                    1          1          1      1   
...                ...        ...        ...    ...   
1253                 2          0          1      0   
1254                 0          2          1      0   
1255                 0          2          0      2   
1256                 0          2          1      2   
1258                 0          2          0      1   

      mental_health_consequence  coworkers  
0                             0          0  
1                             1          1  
2                             0          2  
3                             2          0  
4                             0          0  
...                         ...        ...  
1253                          1          0  
1254                          0          0  
1255                          0          0  
1256                          2          1  
1258                          1          0  

[1161 rows x 16 columns]

In [40]:
import joblib
import pickle
import tensorflow as tf
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [71]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42)

In [76]:
model=tf.keras.Sequential([
    tf.keras.layers.Dense(64,activation="relu"),
    # tf.keras.layers.Dense(10,activation="relu"),
    tf.keras.layers.Dense(1,activation="relu")
])
model.compile(optimizer=tf.optimizers.Adam(learning_rate=0.001),loss=tf.losses.BinaryCrossentropy(),metrics=["accuracy"])

# lr_scheduler=tf.keras.callbacks.LearningRateScheduler(lambda x: 1e-4*10**(x/20))
history=model.fit(x_train,y_train,epochs=150,verbose=0)#,callbacks=lr_scheduler)
model.evaluate(x_train,y_train),model.evaluate(x_test,y_test)

10/10 [==============================] - 0s 1ms/step - loss: 1.0334 - accuracy: 0.7388


([0.3462185859680176, 0.8298850655555725],
 [1.0334320068359375, 0.738831639289856])

In [ ]:
# joblib.dump(model,"model.pkl")

INFO:tensorflow:Assets written to: ram://35913bbe-43ff-4f06-bc6b-57c107485537/assets


['model.pkl']

In [77]:
# pickle.dump(model,open("Model.pkl","wb"))
model.save("Model_new.h5")

In [110]:
k=np.array(x_test)[12]
k=k[np.newaxis,:]
k

array([[0.28, 0.  , 0.  , 0.  , 3.  , 1.  , 0.  , 0.  , 1.  , 1.  , 0.  ,
        1.  , 1.  , 1.  , 1.  , 0.  ]])

In [108]:
y_pred=model.predict(k[np.newaxis,:])
y_pred[0][0]

ValueError: in user code:

    File "c:\Users\Armaan\anaconda3\lib\site-packages\keras\engine\training.py", line 2041, in predict_function  *
        return step_function(self, iterator)
    File "c:\Users\Armaan\anaconda3\lib\site-packages\keras\engine\training.py", line 2027, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\Armaan\anaconda3\lib\site-packages\keras\engine\training.py", line 2015, in run_step  **
        outputs = model.predict_step(data)
    File "c:\Users\Armaan\anaconda3\lib\site-packages\keras\engine\training.py", line 1983, in predict_step
        return self(x, training=False)
    File "c:\Users\Armaan\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None

    ValueError: Exception encountered when calling layer "sequential_32" "                 f"(type Sequential).
    
    Cannot iterate over a shape with unknown rank.
    
    Call arguments received by layer "sequential_32" "                 f"(type Sequential):
      • inputs=tf.Tensor(shape=<unknown>, dtype=float32)
      • training=False
      • mask=None


In [ ]:
# lrs=1e-4*(10**(tf.range(100)/20))
# plt.figure(figsize=(7,4))
# plt.semilogx(lrs,history.history["loss"])
# plt.xlabel("learning_rate")
# plt.ylabel("Loss")

In [123]:
x=[1,2,3]
x=np.array(x).astype(np.float16)
# x[0]=x[0]/100
x[0]=x[0]/100
# x[0]=4
x

array([0.01, 2.  , 3.  ], dtype=float16)

In [103]:
model2=tf.keras.models.load_model('C:\\Users\\Armaan\\OneDrive\\Desktop\\WORKSPACE\\Machine_Learning\\Projects\\Mental illness\\Dataset\\Model_new.h5')

In [109]:
model2.predict(k)[0][0]

1/1 [==============================] - 0s 19ms/step


0.5939277