In [15]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

In [16]:
np.random.seed(2343243)

In [17]:
mean_vec1=np.array([0,0,0])
cov_mat1=np.array([[1,0,0],[0,1,0],[0,0,1]])
class1=np.random.multivariate_normal(mean_vec1,cov_mat1,100)

In [18]:
mean_vec2=np.array([1,1,1])
cov_mat2=np.array([[1,0,0],[0,1,0],[0,0,1]])
class2=np.random.multivariate_normal(mean_vec2,cov_mat2,100)

In [20]:
all_data=np.concatenate((class1,class2))

In [25]:
all_data_t=all_data.T
cov=np.cov(all_data_t)
cov

array([[1.14139998, 0.1061989 , 0.0918139 ],
       [0.1061989 , 1.11579657, 0.27166986],
       [0.0918139 , 0.27166986, 1.11826602]])

In [ ]:
all_data_t=all_data.T
cov=np.cov(all_data_t)
cov

array([[1.14139998, 0.1061989 , 0.0918139 ],
       [0.1061989 , 1.11579657, 0.27166986],
       [0.0918139 , 0.27166986, 1.11826602]])

In [ ]:
all_data_t=all_data.T
cov=np.cov(all_data_t)
cov

array([[1.14139998, 0.1061989 , 0.0918139 ],
       [0.1061989 , 1.11579657, 0.27166986],
       [0.0918139 , 0.27166986, 1.11826602]])

In [ ]:
all_data_t=all_data.T
cov=np.cov(all_data_t)
cov

array([[1.14139998, 0.1061989 , 0.0918139 ],
       [0.1061989 , 1.11579657, 0.27166986],
       [0.0918139 , 0.27166986, 1.11826602]])

In [ ]:
all_data_t=all_data.T
cov=np.cov(all_data_t)
cov

array([[1.14139998, 0.1061989 , 0.0918139 ],
       [0.1061989 , 1.11579657, 0.27166986],
       [0.0918139 , 0.27166986, 1.11826602]])

In [ ]:
all_data_t=all_data.T
cov=np.cov(all_data_t)
cov

array([[1.14139998, 0.1061989 , 0.0918139 ],
       [0.1061989 , 1.11579657, 0.27166986],
       [0.0918139 , 0.27166986, 1.11826602]])

In [ ]:
all_data_t=all_data.T
cov=np.cov(all_data_t)
cov

array([[1.14139998, 0.1061989 , 0.0918139 ],
       [0.1061989 , 1.11579657, 0.27166986],
       [0.0918139 , 0.27166986, 1.11826602]])

In [27]:
eig_val,eig_vec=np.linalg.eig(cov)# eigen vector is column wise

In [36]:
eig_val_vec_pair=[]
for i in range(len(eig_val)):
    eig_v=eig_vec[:,i]
    eig_val_vec_pair.append((eig_val[i],eig_v))
eig_val_vec_pair.sort(reverse=True)
eig_val_vec_pair

[(1.451865341735929, array([0.41124564, 0.64810013, 0.64097055])),
 (1.0786611401978592, array([ 0.91063567, -0.26106644, -0.32029202])),
 (0.8449360955327045, array([ 0.0402454 , -0.71540934,  0.69754554]))]

In [32]:
pca.components_

array([[ 0.41124564,  0.64810013,  0.64097055],
       [ 0.91063567, -0.26106644, -0.32029202]])

In [35]:
pca.explained_variance_

array([1.45186534, 1.07866114])