In [1]:
import tensorflow as tf
# tf.compat.v1.disable_eager_execution()

In [2]:
print(tf.__version__)

2.12.0


In [3]:
# constant tensors

scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#shape of a tensor

scalar.shape

TensorShape([])

In [5]:
vector=tf.constant([10,10,10])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10])>

In [6]:
vector.shape

TensorShape([3])

In [7]:
matrix1=tf.constant([[1,2],[3,4]])
matrix1,matrix1.shape

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>,
 TensorShape([2, 2]))

In [8]:
matrix2=tf.constant([[1.,2.],[3.,5.]])
matrix2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 5.]], dtype=float32)>

In [9]:
matrix3=tf.constant([[1.,2.],[3.,5.],[2.1,4]],dtype=tf.float16)
matrix3,matrix3.shape[0]

(<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[1. , 2. ],
        [3. , 5. ],
        [2.1, 4. ]], dtype=float16)>,
 3)

In [10]:
tensor1=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]],[[4,5,6],[7,8,9]]])
tensor1

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 2, 3]],

       [[4, 5, 6],
        [7, 8, 9]]])>

In [11]:
# tensor variables

mutable_tensor=tf.Variable([1,2])
unmutable_tensor=tf.constant([1,2])
mutable_tensor,unmutable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>)

In [12]:
# mutable_tensor[0].assign(2)

# sess=tf.compat.v1.Session()
# sess.run(tf.compat.v1.global_variables_initializer())
# a=sess.run(unmutable_tensor)
# b=sess.run(mutable_tensor)
tf.print(mutable_tensor)

[1 2]


In [13]:
# random tensors

random_1=tf.compat.v1.random.Generator.from_seed(42) #seed for reproducibility
random_1=random_1.normal(shape=(3,2))
random_2=tf.compat.v1.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [14]:
with tf.compat.v1.Session() as sess:
    sess.run(tf.compat.v1.global_variables_initializer())
    a=sess.run(random_1)
    b=sess.run(random_2)
    print(a,"\n\n",b,"\n\n",a==b)

AttributeError: Tensor.graph is undefined when eager execution is enabled.

In [ ]:
# shuffle a tensor

sess=tf.compat.v1.Session()
a=not_shuffled=tf.constant([[1,2],[2,3],[3,4]])
b=tf.random.shuffle(not_shuffled)
a=sess.run(a)
b=sess.run(b)
a,b

In [ ]:
b=sess.run(tf.random.shuffle(not_shuffled,seed=0))
b

In [ ]:
# Other tensors

a=sess.run(tf.ones([3,2]))
b=sess.run(tf.zeros([3,2,1]))
a,b

In [ ]:
# getting information from tensor

tensor2=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]],[[4,5,6],[7,8,9]]])
print("Datatype:",tensor2.dtype)
print("Rank:",sess.run(tf.rank(tensor2)))
print("Shape:",tensor2.shape)
print("Size:",sess.run(tf.size(tensor2)))

In [ ]:
#Indexing

list=[1,2,3,4]
list[:2]

In [ ]:
sess=tf.compat.v1.Session()
rank_4_tensor=tf.constant([[[[1,2,3],[1,2,3]],
                            [[4,5,6],[4,5,6]]],
                           [[[1,2,3],[1,2,3]],
                            [[4,5,6],[4,5,6]]]])
a=sess.run(rank_4_tensor)
a,a.shape

In [ ]:
a=sess.run(rank_4_tensor[:2,:2,:2,:2])
a

In [ ]:
# first elemet from each dimension except th last one
a=sess.run(rank_4_tensor[:1,:1,:1,:1])
a

In [ ]:
a=sess.run(tf.reshape(rank_4_tensor,shape=(2,-1)))
a

In [ ]:
# Matrices in tensorflow

matrix1=sess.run(tf.constant([[1,2],[3,4],[5,6]]))
matrix2=sess.run(tf.constant([[1,2,3],[4,5,6]]))
mul=sess.run(tf.matmul(matrix1,matrix2))
dot=sess.run(tf.tensordot(matrix1,matrix2,axes=1))
transpose=sess.run(tf.transpose(matrix1))
matrix1,matrix2,mul,transpose,dot

In [ ]:
#changing dtype

tensor1

In [ ]:
tensor3=tf.cast(tensor1,dtype=tf.float16)
tensor3

In [ ]:
#one hot encoding

list=sess.run(tf.constant([1,2,3,0]))
list

In [ ]:
encoded=sess.run(tf.one_hot(list,depth=4))
encoded

In [ ]:
x=tf.compat.v1.placeholder(tf.int32)
y=x*tf.constant(3)
sess.run(y,feed_dict={x:[5,8]})

In [ ]:
x=tf.compat.v1.placeholder(tf.int32,shape=(2,3))
y=x*tf.constant(3)
sess.run(y,feed_dict={x:[[5,8,1],[1,1,1]]})