In [1]:
import numpy as np

In [2]:
x=np.array([[0,0],[1,0],[0,1],[1,1]])
y=np.array([[0,0,0,1]]).T
x.shape,y.shape

((4, 2), (4, 1))

In [3]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [4]:
def derivative_sigmoid(z):
    return (sigmoid(z)*(1-sigmoid(z)))

In [5]:
#no hidden layer weights
weights=2*np.random.random((2,1))-1 # in range -1 to 1
bias=2*np.random.random(1)-1
weights,bias

(array([[ 0.33407104],
        [-0.6452659 ]]),
 array([-0.22881488]))

forward propagation without any hidden layer

In [6]:
lr=0.1
for i in range(10000):
    output0=x
    output=sigmoid((np.dot(output0,weights)+bias))
    first_term=output-y
    #input j =z
    input_for_last_layer=np.dot(output0,weights)+bias
    second_term=derivative_sigmoid(input_for_last_layer)
    first_two=first_term * second_term
    first_two.shape

    changes=np.dot(output0.T,first_two)
    weights=weights-lr*changes
    bias_change=np.sum(first_two)
    bias=bias-lr*bias_change

In [7]:
output=sigmoid((np.dot(output0,weights)+bias))
output

array([[2.46909369e-04],
       [5.56952940e-02],
       [5.56952931e-02],
       [9.33710553e-01]])