In [316]:
import numpy as np

In [317]:
x=np.array([[0,0],[1,0],[0,1],[1,1]])
y=np.array([[0,1,1,1]]).T
x.shape,y.shape 

((4, 2), (4, 1))

In [318]:
y

array([[0],
       [1],
       [1],
       [1]])

In [319]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [320]:
def derivative_sigmoid(z):
    return sigmoid(z)*(1-sigmoid(z))

In [321]:
#no hidden layer weights
#weights=2*np.random.random((2,1))-1 # in range -1 to 1
#bias=2*np.random.random(1)-1
#weights,bias

Forward Propagation


In [322]:
#output0=x
#output=sigmoid(np.dot(output0,weights)+bias)
#output

With Hidden Layers

In [323]:
# 1       1
#         O
# X1             0
#         0   
# X2
#HIDDEN LAYED NEURAL NETWORK

wh=(2*np.random.random((2,2)))-1
bh=(2*np.random.random((1,2)))-1

wo=(2*np.random.random((2,1)))-1
bo=(2*np.random.random((1,1)))-1

Back Tracking\Back Propagation with Hidden Layer

In [324]:
lr=0.05
for i in range(10000):
    
    output0=x
    inputhidden=np.dot(output0,wh)+bh
    outputhidden=sigmoid(inputhidden)
    input_for_outputlayer=np.dot(outputhidden,wo)+bo
    output=sigmoid(input_for_outputlayer)

    first_term_output_layer=output-y
    second_term_output_layer=derivative_sigmoid(input_for_outputlayer)
    first_two_output_layer=first_term_output_layer*second_term_output_layer

    first_term_hidden_layer=first_two_output_layer.dot(wo.T)
    second_term_hidden_layer=derivative_sigmoid(inputhidden)
    first_two_hidden_layer=first_term_hidden_layer*second_term_hidden_layer

    changes_output=outputhidden.T.dot(first_two_output_layer)
    changes_output_bias=np.sum(first_two_output_layer,axis=0,keepdims=True)

    changes_hidden=output0.T.dot(first_two_hidden_layer)
    changes_hidden_bias=np.sum(first_two_hidden_layer,axis=0,keepdims=True)

    wo=wo-lr*changes_output
    bo=bo-lr*changes_output_bias

    wh=wh-lr*changes_hidden
    bh=bh-lr*changes_hidden_bias
    
output0=x
inputhidden=np.dot(output0,wh)
outputhidden=sigmoid(inputhidden)
input_for_outputlayer=np.dot(outputhidden,wo)
output=sigmoid(input_for_outputlayer) 
output,wh,bh,wo,bo


(array([[0.46329394],
        [0.98705909],
        [0.9869969 ],
        [0.99173879]]),
 array([[-3.30531005,  2.7245906 ],
        [-2.67547383,  3.41842396]]),
 array([[ 1.37174651, -1.41714895]]),
 array([[-5.10524856],
        [ 4.81107086]]),
 array([[0.19517066]]))