# NUMPY

In [1]:
import numpy as np

In [3]:
data=np.array([[1,2,3],[4,5,6],[7,8,9]])
m=np.array([[1,1,2],[3,2,2],[2,2,1]])
print(data)
print(m)
print(data*m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 2]
 [3 2 2]
 [2 2 1]]
[[ 1  2  6]
 [12 10 12]
 [14 16  9]]


In [4]:
print((data*m).sum())

82


In [5]:
arr=[0]
arr=np.array(arr)
arr=np.delete(arr,0)
print(arr)

[]


In [7]:
print(np.squeeze([[1,2,3,4],[5,6]]))

[list([1, 2, 3, 4]) list([5, 6])]


c:\Users\Armaan\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:43: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  result = getattr(asarray(obj), method)(*args, **kwds)


In [5]:
m=np.array([1,2,3,4])
n=np.array([1,2,3,4])
m*n+1

array([ 2,  5, 10, 17])

In [2]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])