# Naive Bayes

In [38]:
import numpy as np

In [39]:
def fit(x_train,y_train):
    result={}
    class_values=set(y_train)
    for current_class in class_values:
        result[current_class]={}
        result["total_data"]=len(y_train)
        feature_count=x_train.shape[1]
        current_class_rows=(y_train==current_class)
        x_train_current=x_train[current_class_rows]
        y_train_current=y_train[current_class_rows]
        result[current_class]["total_count"]=len(y_train_current)
        for j in range(feature_count):
            result[current_class][j+1]={}
            all_possible_values=set(x_train[:,j])
            for current_value in all_possible_values:
                result[current_class][j+1][current_value]=x_train_current[x_train_current[:,j]==current_value].sum()
    return result
         

In [40]:
def probability(dictionary,x,current_class):   # current class is different possible values of y
    output=np.log(dictionary[current_class]["total_count"])-np.log(dictionary["total_data"])
    feature_count=len(dictionary[current_class].keys())-1
    for j in range(feature_count):
        fj=x[j]
        count_current_class_with_feature_fj=dictionary[current_class][j+1][fj]+1
        count_current_class=dictionary[current_class]["total_count"]+len(dictionary[current_class][j+1].keys())
        current_xj_probability=np.log(count_current_class_with_feature_fj) - np.log(count_current_class)
        output=output+current_xj_probability
    return output

In [41]:
def predictSinglePoint(dictionary,x):
    classes=dictionary.keys()
    best_p=-1
    best_class=-1
    first_run=True
    for current_class in classes:       # current class is different possible values of y
        if(current_class=="total_data"):
            continue
        p_current_class=probability(dictionary,x,current_class)
        if(first_run==True or p_current_class>best_p):
            best_p=p_current_class
            best_class=current_class
        first_run=False
    return best_class

In [42]:
def predict(dictionary,x_test):
    y_per=[]
    for x in x_test:
        x_class=predictSinglePoint(dictionary,x)
        y_per.append(x_class)
    return y_per

In [43]:
from sklearn.datasets import load_iris
import pandas as pd

iris=load_iris()
x=iris.data
y=iris.target
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [44]:
def makelabelled(column):
    row_count=len(column)
    second_limit=column.mean()
    first_limit=0.5*second_limit
    third_limit=1.5*second_limit
    for i in range(row_count):
        if(column[i]<first_limit):
            column[i]=0
        elif(column[i]<second_limit):
            column[i]=1
        elif(column[i]<third_limit):
            column[i]=2
        else:
            column[i]=3
    return column

In [45]:
for i in range(x.shape[1]):
    x[:,i]=makelabelled(x[:,i])

In [46]:
x

array([[1., 2., 0., 0.],
       [1., 1., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 1., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 1., 0.],
       [1., 1., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 1., 0., 0.],
       [1., 2., 0., 0.],


In [47]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [48]:
dictionary=fit(x_train,y_train)

In [49]:
y_pred=predict(dictionary,x_test)
print(y_pred)

[2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1, 0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1]


In [50]:
from sklearn.metrics import confusion_matrix,classification_report
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.94      1.00      0.97        16
           2       1.00      0.89      0.94         9

    accuracy                           0.97        38
   macro avg       0.98      0.96      0.97        38
weighted avg       0.98      0.97      0.97        38

[[13  0  0]
 [ 0 16  0]
 [ 0  1  8]]
